### ISSUE TITLE
the missing files

### ISSUE THREAD

**Issue by Ming-Di** [priest-yang/ABS-DeepRobotics-Lite3#1]
Hi,how find the missing files, such as `skydroid_gamepad.h` and `lite3_types.h`, for this project? I've checked the repository but couldn't locate them. Any guidance on where to download these files would be greatly appreciated. Thank you!

**Comment by Ming-Di** [comment]
Additionally, where is the `namespace lite3`, thanks

**Comment by priest-yang** [comment]
Hello Ming, could you refer to the official SDK of Lite3? Here is the link: https://github.com/DeepRoboticsLab/Lite3_rl_deploy.

**Comment by Ming-Di** [comment]
> Hello Ming, could you refer to the official SDK of Lite3? Here is the link: https://github.com/DeepRoboticsLab/Lite3_rl_deploy.

Ok  thanks!
